# Generated by Django 5.2.5 on 2025-08-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleResidente',
            fields=[
                ('id_detalle_residente', models.AutoField(primary_key=True, serialize=False)),
                ('propietario', models.BooleanField(default=True)),
                ('apartamento', models.IntegerField()),
                ('torre', models.IntegerField()),
            ],
            options={
                'db_table': 'Detalle_residente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('Rechazada', 'Rechazada'), ('Aprobada', 'Aprobada'), ('En espera', 'En espera')], default='En espera', max_length=15)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_uso', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('forma_pago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], max_length=20)),
            ],
            options={
                'db_table': 'Reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('TI', 'TI'), ('Pasaporte', 'Pasaporte')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=13)),
                ('celular', models.CharField(max_length=13)),
                ('estado', models.CharField(default='Activo', max_length=10)),
                ('contraseña', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonaComun',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_zona', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
                ('tipo_pago', models.CharField(choices=[('Por hora', 'Por hora'), ('Franja horaria', 'Franja horaria'), ('Evento', 'Evento')], max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Zona_comun',
                'managed': False,
            },
        ),
    ]
