# Generated by Django 5.2.5 on 2025-08-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoVehiculo',
            fields=[
                ('idArchivo', models.AutoField(db_column='idArchivo', primary_key=True, serialize=False)),
                ('archivo', models.FileField(db_column='rutaArchivo', upload_to='vehiculos/')),
                ('fechaSubida', models.DateTimeField(auto_now_add=True, db_column='fechaSubida')),
                ('fechaVencimiento', models.DateField(blank=True, db_column='fechaVencimiento', null=True)),
            ],
            options={
                'db_table': 'ArchivoVehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GanadorSorteo',
            fields=[
                ('id_ganador', models.AutoField(db_column='ID_ganador', primary_key=True, serialize=False)),
                ('premio', models.CharField(max_length=100)),
                ('fecha_ganador', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'GanadorSorteo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Noticias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id_sorteo', models.AutoField(db_column='ID_sorteo', primary_key=True, serialize=False)),
                ('fecha_sorteo', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_sorteo', models.TimeField()),
            ],
            options={
                'db_table': 'Sorteo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SorteoVehiculo',
            fields=[
                ('id_sorteo_vehiculo', models.AutoField(db_column='ID_sorteo_vehiculo', primary_key=True, serialize=False)),
                ('fecha_participacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SorteoVehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('idTipoArchivo', models.AutoField(db_column='idTipoArchivo', primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('SOAT', 'SOAT'), ('Tarjeta de propiedad', 'Tarjeta de propiedad'), ('Técnico-mecánica', 'Técnico-mecánica'), ('Licencia', 'Licencia'), ('Identidad', 'Identidad')], max_length=50)),
            ],
            options={
                'db_table': 'TipoArchivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehiculoResidente',
            fields=[
                ('id_vehiculo_residente', models.AutoField(db_column='ID_vehiculo_residente', primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('tipo_vehiculo', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], max_length=10)),
                ('activo', models.BooleanField()),
                ('documentos', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Vehiculo_residente',
                'managed': False,
            },
        ),
    ]
