# Generated by Django 5.2.5 on 2025-09-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_archivovehiculo_ganadorsorteo_noticias_sorteo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id_parqueadero', models.IntegerField(db_column='ID_parqueadero', primary_key=True, serialize=False)),
                ('numero_parqueadero', models.CharField(max_length=6)),
                ('comunal', models.BooleanField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'Parqueadero',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SorteoVehiculo',
        ),
        migrations.AlterModelTable(
            name='ganadorsorteo',
            table='Ganador_sorteo',
        ),
    ]
