# Generated by Django 5.2.5 on 2025-09-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_parqueadero_delete_sorteovehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesParqueadero',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_propietario', models.CharField(choices=[('Visitante', 'Visitante'), ('Residente', 'Residente')], max_length=10)),
                ('registro', models.DateField(auto_now_add=True)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalles_parqueadero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id_visitante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('tipo_vehiculo', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'visitante',
                'managed': False,
            },
        ),
    ]
