# Generated by Django 5.2.5 on 2025-09-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_detallesparqueadero_visitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDeCorres',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField()),
            ],
            options={
                'db_table': 'entrega_de_corres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroCorrespondencia',
            fields=[
                ('id_correspondencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Recibo', 'Recibo'), ('Paquete', 'Paquete')], max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'RegistroCorrespondencia',
                'managed': False,
            },
        ),
    ]
