# Generated by Django 5.2.5 on 2025-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_entregadecorres_registrocorrespondencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaCorrespondencia',
            fields=[
                ('id_Entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEntrega', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'EntregaCorrespondecia',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EntregaDeCorres',
        ),
    ]
