# Generated by Django 5.2.5 on 2025-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_entregacorrespondencia_delete_entregadecorres'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosReserva',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('archivo_1', models.CharField(max_length=255)),
                ('archivo_2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pagos_reserva',
                'managed': False,
            },
        ),
    ]
