# Generated by Django 4.2.24 on 2025-09-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_pagosreserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id_novedad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'novedades',
                'managed': False,
            },
        ),
    ]
