# Generated by Django 4.2.24 on 2025-09-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_codigoverificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodigoVerificacion',
        ),
    ]
