# Generated by Django 4.2.24 on 2025-09-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_delete_codigoverificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
    ]
